apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qenvs-u17c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qenvs-u17c
    app.kubernetes.io/part-of: qenvs-1
  name: qenvs-u17c
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: qenvs-u17c
status:
  loadBalancer: {}
